sudo: required

services:
  - docker

language: php

git:
  depth: 3

php:
  - '7.1'
  - '7.0'
  - '5.6'

install:
  - echo "${TRAVIS_PHP_VERSION}"
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.1" ]]; then composer install; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.0" ]]; then composer update; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.6" ]]; then composer require --dev phpunit/phpunit ^5 --update-with-dependencies; composer update; fi

script:
  - vendor/bin/phpunit tests
  - bin/pipelines --version
  - bin/pipelines --verbose --debug --show
  - bin/pipelines
  - bin/pipelines --pipeline custom/unit-tests || [[ "${TRAVIS_PHP_VERSION}" == "5.6" ]] # known to fail
  - bin/pipelines --pipeline custom/lint-php-5.3
