sudo: required

services:
  - docker

language: php

git:
  depth: 3

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.0snapshot'
  - '7.1snapshot'
  - '7.2snapshot'
  - 'master'

matrix:
  allow_failures:
    - php: 'master'

before_install:
  - openssl aes-256-cbc -K $encrypted_a90e500b3cd1_key -iv $encrypted_a90e500b3cd1_iv -in ktomk-phive-sign.gpg.enc -out ktomk-phive-sign.gpg -d

install:
  - echo "${TRAVIS_PHP_VERSION}"
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.0snapshot" ]]; then composer update; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.0" ]]; then composer update; fi
  - if [[ "${TRAVIS_PHP_VERSION}" == "5.6" ]]; then composer remove --dev friendsofphp/php-cs-fixer phpunit/phpunit; composer require --dev phpunit/phpunit ^5 --update-with-dependencies --no-suggest; fi
  - composer install --no-interaction --no-suggest --no-progress
  - bin/pipelines --images | while read -r image; do docker image pull "$image"; done; true;

script:
  - vendor/bin/phpunit tests
  - composer build
  - gpg --import ktomk-phive-sign.gpg
  - echo "$SIGNPHRASE" | gpg --passphrase-fd 0 --output build/pipelines.phar.asc --detach-sig build/pipelines.phar
  - ls -al build/pipelines.phar.asc
  - bin/pipelines --version
  - bin/pipelines
  - bin/pipelines --verbose --debug --show
  - bin/pipelines --pipeline custom/docker
  - bin/pipelines --pipeline custom/unit-tests
  - bin/pipelines --pipeline custom/lint-php-5.3
  - bin/pipelines --deploy copy --pipeline custom/unit-tests-php-5.3

notifications:
  email: false

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 4xNiXhCoBqLy2CkocUjn2zPKFYr7xod3b02EQ0HG2qNPEJBt+DeZomcck7BsiMcbmbzfTy4vqHX+B5iWmiUMqniYiYwSs28TQYrj6mlY6nav6jfTAkQiLO2Wl/JbV/X1lLIFALGfWkbHgCpgqhF7aOTX9CazcAviqr3WD9CRctlibBTsSdyaBtG9tNrsbjlg4gY/DLBODD4vsbXWok1kXR7gQWy+DeXFvw5BAEOlmI8YP2mpByv7+iGuNSRXIP66xrrIP6OZWooSiNsiNTBcwmUwqu5Ax6QKnY+iWX7oXnzjUsW7JhHmh/dndK8+e/ejPQKjmqGNaJtRFIG+tHKq25Ql32yCmtXTPr1OcJSWtZLPrHLSlptjcVcjXUEoO28CDG3/+3ENcPp3lw3VqVwHb25ySJgLWusiINyYY9tsTZBzeIW5ez/NrPRkjPI8BmJbUSS2eopSPR93WkPF6FURnbLD+aWKPqV4Dj4wCZhldRt+gn0mNmSgm1b/YOUhnlKKctThujmobj5ymoHKQol2GlQwQhLc+J2qThSsw9CvtHUZ4ZXY/+ae/CSIZodcdyZD540YRJoamwiLxUragvOHkeuwjYCZWyw77gUc9jbZVXr8/SCHaA96pCRMwTWPDJYAKJ6jA7mUn9Xb7PxFJxWhFzwPKE8+JSkLTvWVa3JZ66Y=
  file:
    - build/pipelines.phar
    - build/pipelines.phar.asc
  on:
    condition: '$TRAVIS_PHP_VERSION = 7.2'
    tags: true
    repo: ktomk/pipelines

env:
  global:
    secure: 2UP09p6h0NTe+Cwxl8d8d47b5MJjNjx6AmXIg+2zLRc+ggGBhbHAZMk/1TKf8n/j4g0OSXgikdRBkaSGkfQ1jHulWuenuRKwY9/C16lRTXUpcCRQxlHby3twyDBKWhhZs/2dH6iCtyMGi38qmhObh1pmcADrE81PqF6/HBDONIyd2e9m9+Ruq76mWciyiuybm62L0G1kQREphuBIHlCB3aF1hcuO64BcMCrpS5l1q04FQyFx0dOPBKe64HXAjxHOp5bZzAZMmQMhaCKapj+/WddQwyopWDGnqQGgba9nFzGLpb3i+wmWLJJF8QSnVQo4withoE4SzoOgu7fqnpw6s29gYQoJWZ+lT2AupQFQzn1EymvLp9GOco8Wabqc7x1Vl17g+cqlb7qGiYmWm059qmqi0FDs1W3SHrlnpaV4N373IL2pvwKY89yi70fo9M1jyetFezg1jugGKU46v/AjeJ1fKX+6/lxXH7nayke9gbd0GmI0I63r94eCFgy81fIMR7+4J2JhkdP131ZVZMdrgBIgUdPsdFzhTJcZAxZVxeiRy8xAOrlOXrjL9HvGbgcYqENdFEu/0lGeZLvd+W+MqwWfmBbtlLTDVlXoO6Y9VmGODLEePlKSXEiRwMta4zxwCMagzgx1+cNUrb9u09MLjKVlrIpyCG4MM33q0mSiJdg=
