name: CI

on:
  push:
    branches-ignore:
      - travis-ci
  pull_request:

jobs:
  ci:
    name: .travis.yml / PHP ${{ matrix.php-version }} / ${{ matrix.machine }}
    runs-on: ${{ matrix.machine }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        machine: ['ubuntu-18.04']
        php-version: ['8.1', '8.0', '7.4', '7.3', '7.1', '7.0', '5.6']
        experimental: [false]
        xdebug: ['xdebug']
        include:
          - machine: 'ubuntu-18.04'
            php-version: '7.2'
            experimental: false
            xdebug: 'xdebug-2.9.8'

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: yaml

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer
            ~/.cache/pipelines
            vendor
          key: pipelines-${{ hashFiles('**/bitbucket-pipelines.yml') }}-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}-${{ runner.os }}
          restore-keys: |
            composer-${{ hashFiles('**/composer.lock') }}-${{ runner.os }}
            composer-${{ hashFiles('**/composer.lock') }}-
            composer-
            pipelines-${{ hashFiles('**/bitbucket-pipelines.yml') }}-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}-
            pipelines-${{ hashFiles('**/bitbucket-pipelines.yml') }}-${{ hashFiles('**/composer.lock') }}-
            pipelines-${{ hashFiles('**/bitbucket-pipelines.yml') }}-
            pipelines-

      - uses: ktomk/run-travis-yml@v1
        with:
          allow_failure: ${{ matrix.experimental }}
        env:
          TRAVIS_PHP_VERSION: ${{ matrix.php-version }}
